### ISSUE TITLE
Radio Station PRO: Layout occasionally breaks after enabling Continuous Playback

### ISSUE THREAD

**Issue by gusaus** [OpenProducer/newspack-platform#10]
**Describe the bug**
I'm testing Radio Station PRO and the sticky player. When navigating the site some of the pages don't load with the correct layout. For instance, the archive pages load the sidebar content underneath the body. 

I've tested with all Newspack plugins and dependencies disabled (just Radio Station enabled) and the issue remains. 

**To Reproduce**
1. Enable Sitewide Bar Player w/ Continuous Playback Enabled
2. Click categories in the right sidebar (https://radio-openproducer-platform.pantheonsite.io/music/, https://radio-openproducer-platform.pantheonsite.io/news/, https://radio-openproducer-platform.pantheonsite.io/tech/, etc.)
3. Scroll down page
4. Sidebar content will sometimes appear under the body

**Expected behavior**
Widgets should load and appear in the right sidebar

**Screenshots**
See video - 
https://monosnap.com/file/clFqns4DWoq9UzlkypxD0yxjToyzr4

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Firefox 
 - Version 91.0.1 

**Additional context**
I've also switched to the Make theme and experience the same issue...although it happens less frequently. Currently the Make theme is enabled on https://radio-openproducer-platform.pantheonsite.io/

I also realize you use the Make theme on RadioStationDemo.com and don't experience the same issues. 

When Continuous Playback is disabled, the issue goes away.

That said, I'm wondering @majick777 if you had any idea what I could do to troubleshoot. Do you think this is Newspack theme-specific or possibly a configuration issue on my part? 

Ideally, we could get this working with the Newspack theme as it's the base theme for OpenProducer. I'd be happy to test and troubleshoot if someone can point me in the right direction.

Thanks

**Comment by gusaus** [comment]
Reopening this as I'm testing the updated platform (now a ['radio' branch](https://github.com/OpenProducer/newspack-platform/tree/radio) on our Newspack platform with Radio Station 2.4.0.8 + Radio Station PRO 2.4.1.8) and am still getting issues similar to https://github.com/OpenProducer/newspack-platform/issues/10#issuecomment-1083790931. Here are a couple screengrabs. 

**Newspack theme/multiple browsers/Pantheon development environment (https://radio-newspack.pantheonsite.io/)** 
![Music Archives - Newspack Radio 2022-04-25 11-09-30](https://user-images.githubusercontent.com/113996/165148456-b53bf35c-f3ef-4c0c-bfbb-a558a955418d.png)

**Make theme/multiple browsers/local host** 
![Homepage - Newspack Radio 2022-04-25 11-13-12](https://user-images.githubusercontent.com/113996/165148934-ef4cfd13-1dc0-4ccc-ab45-8e0593c9f35d.png)


Here's the debugging info that appears on the screengrab (if you zoom in).

( ! ) Warning: count(): Parameter must be an array or an object that implements Countable in /Users/gusaustin/Local Sites/newspack/app/public/wp-content/plugins/radio-station-pro-premium/teleporter/teleporter.php on line 406
--
1 | 0.0002 | 412392 | {main}( ) | .../index.php:0
2 | 0.0003 | 412664 | require( '/Users/gusaustin/Local Sites/newspack/app/public/wp-blog-header.php' ) | .../index.php:17
3 | 0.4843 | 14347608 | require_once( '/Users/gusaustin/Local Sites/newspack/app/public/wp-includes/template-loader.php' ) | .../wp-blog-header.php:19
4 | 0.4885 | 14372048 | include( '/Users/gusaustin/Local Sites/newspack/app/public/wp-content/themes/make/page.php' ) | .../template-loader.php:106
5 | 0.4885 | 14372048 | get_header( ) | .../page.php:6
6 | 0.4887 | 14373648 | locate_template( ) | .../general-template.php:48
7 | 0.4887 | 14373760 | load_template( ) | .../template.php:716
8 | 0.4888 | 14382328 | require_once( '/Users/gusaustin/Local Sites/newspack/app/public/wp-content/themes/make/header.php' ) | .../template.php:770
9 | 0.4890 | 14382328 | wp_head( ) | .../header.php:9
10 | 0.4890 | 14382328 | do_action( ) | .../general-template.php:3042
11 | 0.4890 | 14382704 | WP_Hook->do_action( ) | .../plugin.php:474
12 | 0.4890 | 14382704 | WP_Hook->apply_filters( ) | .../class-wp-hook.php:331
13 | 0.4892 | 14384928 | wp_enqueue_scripts( ) | .../class-wp-hook.php:307
14 | 0.4892 | 14384928 | do_action( ) | .../script-loader.php:2115
15 | 0.4892 | 14385304 | WP_Hook->do_action( ) | .../plugin.php:474
16 | 0.4892 | 14385304 | WP_Hook->apply_filters( ) | .../class-wp-hook.php:331
17 | 0.5392 | 14681128 | teleporter_enqueue_scripts( ) | .../class-wp-hook.php:307
18 | 0.5395 | 14682488 | teleporter_localize_settings( ) | .../teleporter.php:366


 Any ideas about what this could be?

**Comment by majick777** [comment]
@gusaus Thanks for this! I thought I had already managed to fix that one. 
For the life of me I can't get my head around why the current checks aren't enough...
I opened an issue here for this and updated the Teleporter plugin to 1.0.2 for it:
https://github.com/majick777/teleporter/issues/6
...and added that to the develop branch of Radio Station Pro.
If you can test out with that version, hopefully this issue it finally resolved.

**Comment by gusaus** [comment]
@majick777 Great to hear from you - and thanks for looking into this! 

I'm testing dev on the same environments and it looks like I'm getting another message...

**Newspack theme/multiple browsers/Pantheon development environment (https://radio-newspack.pantheonsite.io/)**
![Homepage - Newspack Radio 2022-04-25 19-55-10](https://user-images.githubusercontent.com/113996/165210769-50a7dbcc-958a-4423-9e6a-bc26550b716d.png)

**Make theme/multiple browsers/local host**
<img width="1181" alt="Homepage - Newspack Radio 2022-04-25 23-46-37" src="https://user-images.githubusercontent.com/113996/165238692-d5e8097a-5165-4c1c-857c-1fe1b7c6b807.png">


Here's the debugging info that appears on the screengrab (if you zoom in)...
 | Time | Memory | Function | Location
-- | -- | -- | -- | --
1 | 0.0003 | 412296 | {main}( ) | .../index.php:0
2 | 0.0004 | 412568 | require( '/Users/gusaustin/Local Sites/newspack/app/public/wp-blog-header.php' ) | .../index.php:17
3 | 0.4158 | 14349024 | require_once( '/Users/gusaustin/Local Sites/newspack/app/public/wp-includes/template-loader.php' ) | .../wp-blog-header.php:19
4 | 0.4220 | 14373464 | include( '/Users/gusaustin/Local Sites/newspack/app/public/wp-content/themes/make/page.php' ) | .../template-loader.php:106
5 | 0.4220 | 14373464 | get_header( ) | .../page.php:6
6 | 0.4222 | 14375064 | locate_template( ) | .../general-template.php:48
7 | 0.4222 | 14375176 | load_template( ) | .../template.php:716
8 | 0.4222 | 14383744 | require_once( '/Users/gusaustin/Local Sites/newspack/app/public/wp-content/themes/make/header.php' ) | .../template.php:770
9 | 0.4225 | 14383744 | wp_head( ) | .../header.php:9
10 | 0.4225 | 14383744 | do_action( ) | .../general-template.php:3042
11 | 0.4225 | 14384120 | WP_Hook->do_action( ) | .../plugin.php:474
12 | 0.4225 | 14384120 | WP_Hook->apply_filters( ) | .../class-wp-hook.php:331
13 | 0.4226 | 14386344 | wp_enqueue_scripts( ) | .../class-wp-hook.php:307
14 | 0.4226 | 14386344 | do_action( ) | .../script-loader.php:2115
15 | 0.4226 | 14386720 | WP_Hook->do_action( ) | .../plugin.php:474
16 | 0.4226 | 14386720 | WP_Hook->apply_filters( ) | .../class-wp-hook.php:331
17 | 0.4418 | 14470208 | teleporter_enqueue_scripts( ) | .../class-wp-hook.php:307
18 | 0.4421 | 14471568 | teleporter_localize_settings( ) | .../teleporter.php:366
19 | 0.4423 | 14474576 | apply_filters( ) | .../teleporter.php:400
20 | 0.4423 | 14474976 | WP_Hook->apply_filters( ) | .../plugin.php:189


Hope that helps. I'll be happy to test further tomorrow. Thanks!

**Comment by majick777** [comment]
@gusaus Erk yeah whoops, that was added for a smaller Teleporter issue https://github.com/majick777/teleporter/issues/3
Just added a missing prefix to the function name and pushed it back to Radio Station Pro develop, that should fix that.
Thanks again for picking that up!
I also just made a slight fix to RSP so that if you are playing and transition to a new page via Teleporter, the Show info AND track meta display (if any) appear when loaded (rather than waiting for the metadata to reload.) :-)

**Comment by gusaus** [comment]
@majick777 Testing now and I'm getting a slightly different warning...

**Newspack theme/multiple browsers/Pantheon development environment (https://radio-newspack.pantheonsite.io/)**
![Schedule - Newspack Radio 2022-04-26 10-22-00](https://user-images.githubusercontent.com/113996/165357121-0df93a4c-9cc2-4e58-889b-170b6b897720.png)

**Make theme/multiple browsers/local host**
![Homepage - Newspack Radio 2022-04-26 10-23-01](https://user-images.githubusercontent.com/113996/165357310-6d2dfcfe-cd06-404d-aa65-97d652e2efc5.png)

Here's the debugging info that appears on the screengrab (if you zoom in)...

Warning: count(): Parameter must be an array or an object that implements Countable in /Users/gusaustin/Local Sites/newspack/app/public/wp-content/plugins/radio-station-pro-premium/teleporter/teleporter.php on line 417

Time | Memory | Function | Location
-- | -- | -- | -- | --
1 | 0.0004 | 412328 | {main}( ) | .../index.php:0
2 | 0.0004 | 412600 | require( '/Users/gusaustin/Local Sites/newspack/app/public/wp-blog-header.php' ) | .../index.php:17
3 | 0.4595 | 14349064 | require_once( '/Users/gusaustin/Local Sites/newspack/app/public/wp-includes/template-loader.php' ) | .../wp-blog-header.php:19
4 | 0.4652 | 14373504 | include( '/Users/gusaustin/Local Sites/newspack/app/public/wp-content/themes/make/page.php' ) | .../template-loader.php:106
5 | 0.4652 | 14373504 | get_header( ) | .../page.php:6
6 | 0.4655 | 14375104 | locate_template( ) | .../general-template.php:48
7 | 0.4655 | 14375216 | load_template( ) | .../template.php:716
8 | 0.4662 | 14383784 | require_once( '/Users/gusaustin/Local Sites/newspack/app/public/wp-content/themes/make/header.php' ) | .../template.php:770
9 | 0.4664 | 14383784 | wp_head( ) | .../header.php:9
10 | 0.4664 | 14383784 | do_action( ) | .../general-template.php:3042
11 | 0.4664 | 14384160 | WP_Hook->do_action( ) | .../plugin.php:474
12 | 0.4664 | 14384160 | WP_Hook->apply_filters( ) | .../class-wp-hook.php:331
13 | 0.4666 | 14386384 | wp_enqueue_scripts( ) | .../class-wp-hook.php:307
14 | 0.4666 | 14386384 | do_action( ) | .../script-loader.php:2115
15 | 0.4666 | 14386760 | WP_Hook->do_action( ) | .../plugin.php:474
16 | 0.4666 | 14386760 | WP_Hook->apply_filters( ) | .../class-wp-hook.php:331
17 | 0.5116 | 14682584 | teleporter_enqueue_scripts( ) | .../class-wp-hook.php:307
18 | 0.5119 | 14683944 | teleporter_localize_settings( ) | .../teleporter.php:366

I should be around to test and help troubleshoot today.

**Comment by gusaus** [comment]
@tonyzeoli @majick777 I'm confused (as usual :confused:) though... as it looks like this is 'not' a Pantheon specific issue (as we previously thought it was), is it specific to Newspack? Assuming this would have been reported by others if it was a common problem with Radio Station PRO.

**Comment by majick777** [comment]
@gusaus What version of PHP version are you using? This might show in PHP7.x or only in 8. As I said, I have seen this error before and thought I'd fixed it already. 

It's a warning rather than an error, so won't prevent loading and unless someone has debugging mode turned on, they won't see it anyway. On that note, if you are displaying rather than logging errors, it's worth being aware that this can cause a cascade into other unforeseen errors with "headers already sent" and can affect redirects and cookies etc. Better practice is to use a proper debugger, or an error handler class and output the errors on shutdown. (I've written an error handler class for this if you'd like to try it.)

Finally, I am staring at this code as I have a few times already, scratching my head and it dawned on me that:
`( count( $ignore_classes > 0 ) )` is wrong after all.
`( count( $ignore_classes ) > 0 )` is what is should be. 
Sooo, just a simple bracket misplacement typo after all that. *facepalm*

Try it now I've pushed another update to fix this and another improvement to the player page transitions.

**Comment by gusaus** [comment]
@majick777 It looks like the last fix got rid of the warnings!! This is great progress, thanks!!

That said, we might still be experiencing some of the layout/performance issues as noted in the issue description https://github.com/OpenProducer/newspack-platform/issues/10.

Here are some notes/links pertaining to the current 'Newspack' development environment (by the way, I set you and @tonyzeoli  as admins) -
https://radio-newspack.pantheonsite.io/

The development environment is powered by this repo/branch - 
https://github.com/OpenProducer/newspack-platform/tree/radio

The PHP version is 7.4

Here's a screengrab of the current Sitewide Bar Player settings
![Homepage - Newspack Radio 2022-04-27 09-36-30](https://user-images.githubusercontent.com/113996/165571247-0160bb9a-e8d3-4288-ac0c-113ff1bbb16f.png)


I was going to upload a video capturing my experience browsing the current environment but I'm having issues with Monosnap...

....generally speaking, the sound takes awhile to come on after hitting play. The transitions from page to page seems a bit laggy (could be my settings?). Some of the layouts are a bit off... those could well be issues related to Newspack and/or the particular Newspack theme and not directly related to the player.

Again, you both have admin access - maybe you can test out yourself and share your thoughts. 

Thanks!

**Comment by gusaus** [comment]
So I updated to the latest versions of Radio Station (Version 2.4.0.9) + Radio Station PRO (Version 2.4.1.9) and the warnings reported in this issue are gone! 

That said, there are issues that most likely need to be addressed (see my previous comment) before Newspack adds to their list of [approved third-party plugins](https://docs.google.com/spreadsheets/d/1cOxvYjn57lV2mNU7ExiP1PRJOERDKoyDfO1I5T46DqY/edit#gid=0) (see https://newspack.pub/support/plugins/). The paid beta offering [we're discussing](https://github.com/OpenProducer/community/discussions/26) should provide us with the resources needed for Newspack to recommend along with an opportunity to collaborate/partner with their team. Especially if someone from the Netmix/Radio Station PRO is able to [commit to the PM role](https://github.com/OpenProducer/community/discussions/26#discussioncomment-2563945).

**Comment by gusaus** [comment]
Closing as it we're no longer including or supporting Radio Station PRO in this repo.
